#  ❖  BTC 1‑minute OHLCV dataset  ❖
model_type: lstm
seq_length: 60            # 60 mins ≈ 1‑hour look‑back for momentum
data:
  train: code/stc/data/processed/CRYPTO_TICK/BTC_1min.parquet         # full file contains all rows; we'll split by time
  val:   code/src/data/processed/CRYPTO_TICK/BTC_1min.parquet         # same file ‑ train/val cut handled in loader if desired
  label: y_class
model:
  units: [64, 32]
  dropout: 0.20
training:
  batch: 128
  epochs: 25
  patience: 6
  class_weight: true        # BTC 1‑min still ~75 % stationary → mild weight helps
  model_out: results/models/btc1m_lstm.h5
  scaler_json: results/scalers/btc1m.json


# train: data/processed/CRYPTO_TICK/BTC_1sec.parquet
# val:   data/processed/CRYPTO_TICK/BTC_1sec.parquet
# seq_length: 300          # e.g., 5‑minute look‑back if using 1‑sec bars
